apiVersion: apps/v1
kind: Deployment
metadata:
  name: volumes-new
  namespace: volume2
spec:
  selector:
    matchLabels:
      app: volumes2
  replicas: 1
  template:
    metadata:
      labels:
        app: volumes2
    spec:
      nodeSelector:
        kubernetes.io/hostname: linux-devops
      containers:
        - name: busybox
          image: busybox
          command: ['sh', '-c', 'mkdir -p /out/logs && while true; do echo "$(date) - Test message" >> /out/logs/test.txt; sleep 5; done']
          volumeMounts:
            - name: volume
              mountPath: /out/logs
        - name: multitool
          image: wbitt/network-multitool
          command: ['sh', '-c', 'tail -f /out/logs/test.txt']
          volumeMounts:
            - name: volume
              mountPath: /out/logs
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: pvc-vol