apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool
  namespace: volume2
  labels:
    app: multitool
spec:
  selector:
    matchLabels:
      app: multitool
  replicas: 1
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool
          ports:
            - containerPort: 8080
          env:
            - name: HTTP_PORT
              value: "1180"
          volumeMounts:
            - name: nfs-volume
              mountPath: "/data"
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: nfs-pvc